[theme]
base = "light"
primaryColor = "#087f8c"
backgroundColor = "#fbfcfe"
secondaryBackgroundColor = "#f0f4f8"
textColor = "#142235"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
